#!/usr/bin/env bash
# Generated by 2-generate.py
# Do not edit directly — edit 1-config.yaml and regenerate.

set -euo pipefail

log() { printf "\n\033[1;34m==> %s\033[0m\n" "$1"; }
ok()  { printf "    \033[0;32mOK: %s\033[0m\n" "$1"; }

if [[ $EUID -eq 0 ]]; then
    echo "Run this script as a normal user, not as root."
    exit 1
fi
if ! command -v sudo >/dev/null 2>&1; then
    echo "sudo is required but was not found."
    exit 1
fi
if ! command -v curl >/dev/null 2>&1; then
    echo "curl is required but was not found."
    exit 1
fi

log "Installing apt packages..."
sudo apt-get update -qq
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
    git \
    libbz2-dev \
    libffi-dev \
    liblzma-dev \
    libncursesw5-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    openssh-client \
    tk-dev \
    zlib1g-dev
ok "apt packages installed"

if command -v zoxide > /dev/null 2>&1; then
    log "zoxide already installed — to update, see the tool's own documentation"
else
    log "Installing zoxide..."
    curl -fsSL https://raw.githubusercontent.com/ajeetdsouza/zoxide/main/install.sh | bash
    ok "zoxide installed"
fi

if [ -d "$HOME/.pyenv" ] > /dev/null 2>&1; then
    log "pyenv already installed — to update, see the tool's own documentation"
else
    log "Installing pyenv..."
    curl -fsSL https://pyenv.run | bash
    ok "pyenv installed"
fi
