#!/usr/bin/env bash
# Generated by 2-generate.py
# Do not edit directly — edit 1-config.yaml and regenerate.

set -euo pipefail

log() { printf "\n\033[1;34m==> %s\033[0m\n" "$1"; }
ok()  { printf "    \033[0;32mOK: %s\033[0m\n" "$1"; }

if [[ $EUID -eq 0 ]]; then
    echo "Run this script as a normal user, not as root."
    exit 1
fi
if ! command -v sudo >/dev/null 2>&1; then
    echo "sudo is required but was not found."
    exit 1
fi

log "Bootstrapping prerequisites..."
sudo apt-get update -qq
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl ca-certificates
ok "Prerequisites ready"

log "Configuring custom repositories..."

# mise
if ! mise ls > /dev/null 2>&1; then
    sudo install -dm 755 /etc/apt/keyrings
    curl -fsSL https://mise.jdx.dev/gpg-key.pub | sudo tee /etc/apt/keyrings/mise-archive-keyring.asc 1> /dev/null
    echo "deb [signed-by=/etc/apt/keyrings/mise-archive-keyring.asc] https://mise.jdx.dev/deb stable main" | sudo tee /etc/apt/sources.list.d/mise.list
fi

ok "Custom repositories configured"

log "Installing apt packages..."
sudo apt-get update -qq
sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
    bat \
    btop \
    build-essential \
    ca-certificates \
    csh \
    curl \
    git \
    git-delta \
    gnupg \
    jq \
    mc \
    mise \
    openssh-server \
    qemu-guest-agent \
    ripgrep \
    unzip \
    visidata \
    wget \
    xz-utils \
    zsh
ok "apt packages installed"

log "Installing mise-managed tools..."
mise install
ok "mise tools installed"

log "Setup complete!"
echo ""
echo "Next steps:"
echo "  4-post-install-steps.md — Review before you start: a few short steps will have the system up and running"
echo "  tool-reference.md       — reference guide for installed tools"
echo ""
