#!/usr/bin/env bash
# Generated by generate.py from tools.yaml on 2026-03-05 04:11 UTC
# DO NOT edit this file directly — edit tools.yaml and re-run: python3 generate.py
# bootstrap.sh — Ubuntu 24.04.x LTS TUI workbench bootstrap
# Run as a normal user. Uses sudo where needed.
set -euo pipefail

LOGFILE="$HOME/bootstrap.log"
mkdir -p "$(dirname "$LOGFILE")"
exec > >(tee -a "$LOGFILE") 2>&1
trap 'rc=$?; echo "Bootstrap finished with exit code $rc at $(date -Is)"; exit $rc' EXIT

echo "Bootstrap started: $(date -Is)"
echo "Logfile: $LOGFILE"

log()  { printf "\n==> %s\n" "$*"; }
ok()   { printf "    \u2713 %s\n" "$*"; }
warn() { printf "    ! %s\n" "$*"; }

ensure_block() {
  local marker="$1" content="$2"
  if ! grep -qF "$marker" "$HOME/.zshrc"; then
    printf "\n%s\n%s\n" "$marker" "$content" >> "$HOME/.zshrc"
    ok "Added block: $marker"
  else
    ok "Block already present: $marker"
  fi
}

fetch_latest_version() {
  curl -fsSL "https://api.github.com/repos/$1/releases/latest" | jq -r '.tag_name' | sed 's/^v//'
}

install_release_binary_tarball() {
  local version="$1" url_tpl="$2" bin_in="$3" target="$4"
  local url tmp
  url="${url_tpl//\{version\}/$version}"
  tmp="$(mktemp -d)"
  curl -fsSL "$url" -o "$tmp/pkg.tgz"
  tar -xzf "$tmp/pkg.tgz" -C "$tmp" "$bin_in"
  install -m 755 "$tmp/$bin_in" "$HOME/.local/bin/$target"
  rm -rf "$tmp"
}

semver_lt() {
  [[ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | head -n1)" == "$1" && "$1" != "$2" ]]
}

if [[ $EUID -eq 0 ]]; then echo "Run as a normal user (not root)."; exit 1; fi
command -v sudo >/dev/null 2>&1 || { echo "sudo is required."; exit 1; }

echo "User: $USER  Host: $(hostname)  Ubuntu: $(lsb_release -ds 2>/dev/null || true)"
touch "$HOME/.zshrc"

log "APT: update + baseline packages"
sudo apt-get update
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install software-properties-common
sudo add-apt-repository -y universe
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install \
    ca-certificates \
    curl \
    wget \
    git \
    unzip \
    xz-utils \
    jq \
    gnupg \
    build-essential \
    zsh \
    mc \
    btop \
    ripgrep \
    openssh-server \
    qemu-guest-agent
ok "Baseline apt packages installed"

log "Services"
sudo systemctl enable --now ssh
sudo systemctl enable --now qemu-guest-agent
ok "Services enabled"

log "SSH hardening drop-in"
DROPIN="/etc/ssh/sshd_config.d/99-workbench-hardening.conf"
if [[ ! -f "$DROPIN" ]]; then
  sudo tee "$DROPIN" >/dev/null <<'EOC'
# Workbench SSH hardening (safe defaults)
PermitRootLogin no
X11Forwarding no
MaxAuthTries 4
ClientAliveInterval 300
ClientAliveCountMax 2

# After you've confirmed key-based login works, uncomment:
# PasswordAuthentication no
# KbdInteractiveAuthentication no
# ChallengeResponseAuthentication no
# PubkeyAuthentication yes
EOC
  sudo sshd -t
  sudo systemctl reload ssh
  ok "sshd drop-in created: $DROPIN"
else
  ok "sshd drop-in already exists (skipping)"
fi

log "Default shell → zsh"
SHELL_PATH="$(command -v zsh)"
CURRENT_SHELL="$(getent passwd "$USER" | cut -d: -f7 || true)"
if [[ "$CURRENT_SHELL" != "$SHELL_PATH" ]]; then
  sudo chsh -s "$SHELL_PATH" "$USER"
  ok "Default shell set to zsh"
else
  ok "zsh already default"
fi

log "PATH setup"
mkdir -p $HOME/.local/bin $HOME/.npm-global/bin

ensure_block "# --- workbench: ~/.local/bin ---" 'export PATH="$HOME/.local/bin:$PATH"'
ensure_block "# --- workbench: ~/.npm-global/bin ---" 'export PATH="$HOME/.npm-global/bin:$PATH"'
export PATH="$HOME/.local/bin:$HOME/.npm-global/bin:$PATH"
ok "PATH configured"

log "Repo: gh"
if [[ ! -f /etc/apt/sources.list.d/github-cli.list ]]; then
  sudo mkdir -p -m 755 /etc/apt/keyrings
  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg >/dev/null
  sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg
  echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list >/dev/null
  ok "gh repo added"
else
  ok "gh repo already present"
fi

log "Repo: nodejs"
curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
ok "nodejs repo configured"

log "Repo: glow  # Markdown renderer — from Charm"
if [[ ! -f /etc/apt/sources.list.d/charm.list ]]; then
  sudo mkdir -p -m 755 /etc/apt/keyrings
  curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
  sudo chmod a+r /etc/apt/keyrings/charm.gpg
  echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list >/dev/null
  ok "glow repo added"
else
  ok "glow repo already present"
fi

sudo apt-get update
log "Installing repo-backed packages: gh nodejs glow"
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install gh nodejs glow
ok "Repo-backed packages installed"

log "Install: zellij  # Terminal multiplexer (prefer over tmux)"
ZELLIJ_VER="$(fetch_latest_version zellij-org/zellij)"
if ! command -v zellij >/dev/null 2>&1; then
  install_release_binary_tarball \
    "$ZELLIJ_VER" \
    "https://github.com/zellij-org/zellij/releases/download/v{version}/zellij-x86_64-unknown-linux-musl.tar.gz" \
    "zellij" \
    "zellij"
  ok "zellij v$ZELLIJ_VER installed"
else
  ok "zellij already present (maintenance will keep it current)"
fi

log "Install: lazygit"
LAZYGIT_VER="$(fetch_latest_version jesseduffield/lazygit)"
if ! command -v lazygit >/dev/null 2>&1; then
  install_release_binary_tarball \
    "$LAZYGIT_VER" \
    "https://github.com/jesseduffield/lazygit/releases/download/v{version}/lazygit_{version}_Linux_x86_64.tar.gz" \
    "lazygit" \
    "lazygit"
  ok "lazygit v$LAZYGIT_VER installed"
else
  ok "lazygit already present (maintenance will keep it current)"
fi

log "npm: @openai/codex"
npm config set prefix "$HOME/.npm-global"
if ! command -v codex >/dev/null 2>&1; then
  npm install -g @openai/codex
  ok "codex installed"
else
  ok "codex already installed"
fi

                log "Install: pyenv"
                if ! [ -d "$HOME/.pyenv" ]; then
                  sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install \
    libssl-dev \
    zlib1g-dev \
    libbz2-dev \
    libreadline-dev \
    libsqlite3-dev \
    libncursesw5-dev \
    libffi-dev \
    liblzma-dev \
    tk-dev
  curl -fsSL https://pyenv.run | bash
                  ok "pyenv installed"
                else
                  ok "pyenv already present"
                fi
ensure_block "# --- workbench: pyenv ---" \
'export PYENV_ROOT="$HOME/.pyenv"
[[ -d "$PYENV_ROOT/bin" ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"
if [[ -d "$PYENV_ROOT/plugins/pyenv-virtualenv" ]]; then
  eval "$(pyenv virtualenv-init -)"
fi'

log "Install: claude  # Claude Code CLI — self-updates, no maintenance step needed"
if ! command -v claude || [ -x "$HOME/.local/bin/claude" ]; then
    curl -fsSL https://claude.ai/install.sh | bash
  ok "claude installed"
else
  ok "claude already present"
fi

log "Git clone: zsh-completions"
if [[ ! -d "$HOME/.zsh/zsh-completions" ]]; then
  git clone --depth=1 https://github.com/zsh-users/zsh-completions.git "$HOME/.zsh/zsh-completions"
  ok "zsh-completions cloned"
else
  ok "zsh-completions already present"
fi
ensure_block "# --- workbench: zsh-completions ---" \
'fpath=("$HOME/.zsh/zsh-completions/src" $fpath)'

log "APT cleanup"
sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" autoremove
ok "Done"

NEXT_STEPS="$HOME/bootstrap-next-steps.md"
cat > "$NEXT_STEPS" <<NEXTSTEPS
# Bootstrap Next Steps
Generated: $(date -Is)

## Manual actions required

- [ ] Re-login (or: exec zsh) to activate new default shell and PATH.
- [ ] SSH hardening: after confirming key-based login works, edit
    /etc/ssh/sshd_config.d/99-workbench-hardening.conf
  and uncomment: PasswordAuthentication no
  then: sudo systemctl reload ssh
- [ ] gh auth login
- [ ] Set OPENAI_API_KEY in your shell, or run: codex  (follow prompts)
- [ ] claude  # follow prompts to authenticate
NEXTSTEPS

log "Bootstrap complete"
echo ""
echo "Next steps written to: $NEXT_STEPS"
echo ""
glow "$NEXT_STEPS" 2>/dev/null || cat "$NEXT_STEPS"
