#!/usr/bin/env python3
"""
generate.py — reads tools.yaml, writes bootstrap.sh and maintenance.sh
Run: python3 generate.py
"""
import sys
import textwrap
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required: pip install pyyaml")

TOOLS_YAML = Path(__file__).parent / "tools.yaml"
BOOTSTRAP_OUT = Path(__file__).parent / "bootstrap.sh"
MAINTENANCE_OUT = Path(__file__).parent / "maintenance.sh"

GENERATED_BANNER = f"# Generated by generate.py from tools.yaml on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}"
DO_NOT_EDIT = "# DO NOT edit this file directly — edit tools.yaml and re-run: python3 generate.py"

APT_NI = 'DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"'

SHARED_HELPERS = r"""
log()  { printf "\n==> %s\n" "$*"; }
ok()   { printf "    \u2713 %s\n" "$*"; }
warn() { printf "    ! %s\n" "$*"; }

ensure_block() {
  local marker="$1" content="$2"
  if ! grep -qF "$marker" "$HOME/.zshrc"; then
    printf "\n%s\n%s\n" "$marker" "$content" >> "$HOME/.zshrc"
    ok "Added block: $marker"
  else
    ok "Block already present: $marker"
  fi
}

fetch_latest_version() {
  curl -fsSL "https://api.github.com/repos/$1/releases/latest" | jq -r '.tag_name' | sed 's/^v//'
}

install_release_binary_tarball() {
  local version="$1" url_tpl="$2" bin_in="$3" target="$4"
  local url tmp bin_path
  url="${url_tpl//\{version\}/$version}"
  tmp="$(mktemp -d)"
  curl -fsSL "$url" -o "$tmp/pkg.tgz"
  tar -xzf "$tmp/pkg.tgz" -C "$tmp"
  bin_path="$(find "$tmp" -name "$bin_in" -type f | head -1)"
  install -m 755 "$bin_path" "$HOME/.local/bin/$target"
  rm -rf "$tmp"
}

semver_lt() {
  [[ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | head -n1)" == "$1" && "$1" != "$2" ]]
}
"""

# ── helpers ──────────────────────────────────────────────────────────────────

def indent(text, n=2):
    pad = " " * n
    return "\n".join(pad + line if line.strip() else line for line in text.splitlines())

def note_comment(entry):
    note = entry.get("note", "")
    return f"  # {note}" if note else ""

def collect_actions(cfg):
    """Return list of (name, action_required) for all entries that have one."""
    actions = []
    for section in ("apt_repos", "npm", "curl_installers", "github_releases"):
        for entry in cfg.get(section, []):
            if "action_required" in entry:
                actions.append((entry["name"], entry["action_required"]))
    return actions


# ── bootstrap sections ────────────────────────────────────────────────────────

def bs_header():
    return f"""\
#!/usr/bin/env bash
{GENERATED_BANNER}
{DO_NOT_EDIT}
# bootstrap.sh — Ubuntu 24.04.x LTS TUI workbench bootstrap
# Run as a normal user. Uses sudo where needed.
set -euo pipefail

LOGFILE="$HOME/bootstrap.log"
mkdir -p "$(dirname "$LOGFILE")"
exec > >(tee -a "$LOGFILE") 2>&1
trap 'rc=$?; echo "Bootstrap finished with exit code $rc at $(date -Is)"; exit $rc' EXIT

echo "Bootstrap started: $(date -Is)"
echo "Logfile: $LOGFILE"
{SHARED_HELPERS}
if [[ $EUID -eq 0 ]]; then echo "Run as a normal user (not root)."; exit 1; fi
command -v sudo >/dev/null 2>&1 || {{ echo "sudo is required."; exit 1; }}

echo "User: $USER  Host: $(hostname)  Ubuntu: $(lsb_release -ds 2>/dev/null || true)"
touch "$HOME/.zshrc"
"""

def bs_apt(cfg):
    pkgs = " \\\n    ".join(cfg.get("apt", []))
    return f"""\
log "APT: update + baseline packages"
sudo apt-get update
sudo {APT_NI} install software-properties-common
sudo add-apt-repository -y universe
sudo {APT_NI} upgrade
sudo {APT_NI} install \\
    {pkgs}
ok "Baseline apt packages installed"
"""

def bs_services(cfg):
    lines = []
    for svc in cfg.get("services", []):
        lines.append(f"sudo systemctl enable --now {svc}")
    if not lines:
        return ""
    body = "\n".join(lines)
    return f"""\
log "Services"
{body}
ok "Services enabled"
"""

def bs_ssh_hardening():
    return r"""log "SSH hardening drop-in"
DROPIN="/etc/ssh/sshd_config.d/99-workbench-hardening.conf"
if [[ ! -f "$DROPIN" ]]; then
  sudo tee "$DROPIN" >/dev/null <<'EOC'
# Workbench SSH hardening (safe defaults)
PermitRootLogin no
X11Forwarding no
MaxAuthTries 4
ClientAliveInterval 300
ClientAliveCountMax 2

# After you've confirmed key-based login works, uncomment:
# PasswordAuthentication no
# KbdInteractiveAuthentication no
# ChallengeResponseAuthentication no
# PubkeyAuthentication yes
EOC
  sudo sshd -t
  sudo systemctl reload ssh
  ok "sshd drop-in created: $DROPIN"
else
  ok "sshd drop-in already exists (skipping)"
fi
"""

def bs_shell(cfg):
    shell = cfg.get("shell", "zsh")
    return f"""\
log "Default shell → {shell}"
SHELL_PATH="$(command -v {shell})"
CURRENT_SHELL="$(getent passwd "$USER" | cut -d: -f7 || true)"
if [[ "$CURRENT_SHELL" != "$SHELL_PATH" ]]; then
  sudo chsh -s "$SHELL_PATH" "$USER"
  ok "Default shell set to {shell}"
else
  ok "{shell} already default"
fi
"""

def bs_paths(cfg):
    lines = []
    for p in cfg.get("paths", []):
        expanded = p.replace("~", "$HOME")
        marker = f"# --- workbench: {p} ---"
        lines.append(f'ensure_block "{marker}" \'export PATH="{expanded}:$PATH"\'')
    dirs = " ".join(p.replace("~", "$HOME") for p in cfg.get("paths", []))
    export = ":".join(p.replace("~", "$HOME") for p in cfg.get("paths", []))
    return f"""\
log "PATH setup"
mkdir -p {dirs}
{"".join(chr(10) + l for l in lines)}
export PATH="{export}:$PATH"
ok "PATH configured"
"""

def bs_apt_repos(cfg):
    chunks = []
    pkgs = []
    for entry in cfg.get("apt_repos", []):
        name = entry["name"]
        nc = note_comment(entry)
        pkg = entry["package"]
        pkgs.append(pkg)

        if "setup_script" in entry:
            chunks.append(f"""\
log "Repo: {name}{nc}"
curl -fsSL {entry['setup_script']} | sudo -E bash -
ok "{name} repo configured"
""")
        else:
            src_file = entry["source_file"]
            key_url = entry["key_url"]
            key_path = entry["key_path"]
            source = entry["source"].replace("{arch}", "$(dpkg --print-architecture)")
            if entry.get("key_dearmor"):
                key_cmd = f'curl -fsSL {key_url} | sudo gpg --dearmor -o {key_path}\n  sudo chmod a+r {key_path}'
            else:
                key_cmd = f'curl -fsSL {key_url} | sudo tee {key_path} >/dev/null\n  sudo chmod go+r {key_path}'
            chunks.append(f"""\
log "Repo: {name}{nc}"
if [[ ! -f {src_file} ]]; then
  sudo mkdir -p -m 755 /etc/apt/keyrings
  {key_cmd}
  echo "{source}" | sudo tee {src_file} >/dev/null
  ok "{name} repo added"
else
  ok "{name} repo already present"
fi
""")

    pkg_list = " ".join(pkgs)
    chunks.append(f"""\
sudo apt-get update
log "Installing repo-backed packages: {pkg_list}"
sudo {APT_NI} install {pkg_list}
ok "Repo-backed packages installed"
""")
    return "\n".join(chunks)

def bs_github_releases(cfg):
    chunks = []
    for entry in cfg.get("github_releases", []):
        name = entry["name"]
        repo = entry["repo"]
        url_tpl = entry["url"].replace("{repo}", repo)
        binary = entry["binary"]
        nc = note_comment(entry)

        zshrc = entry.get("zshrc_block")
        zshrc_block = ""
        if zshrc:
            content = zshrc["content"].rstrip()
            marker = zshrc["marker"]
            zshrc_block = f'\nensure_block "{marker}" \\\n\'{content}\''

        chunks.append(f"""\
log "Install: {name}{nc}"
{name.upper()}_VER="$(fetch_latest_version {repo})"
if ! command -v {name} >/dev/null 2>&1; then
  install_release_binary_tarball \\
    "${name.upper()}_VER" \\
    "{url_tpl}" \\
    "{binary}" \\
    "{name}"
  ok "{name} v${name.upper()}_VER installed"
else
  ok "{name} already present (maintenance will keep it current)"
fi{zshrc_block}
""")
    return "\n".join(chunks)

def bs_npm(cfg):
    chunks = []
    for entry in cfg.get("npm", []):
        name = entry["name"]
        bin_ = entry["bin"]
        nc = note_comment(entry)
        chunks.append(f"""\
log "npm: {name}{nc}"
npm config set prefix "$HOME/.npm-global"
if ! command -v {bin_} >/dev/null 2>&1; then
  npm install -g {name}
  ok "{bin_} installed"
else
  ok "{bin_} already installed"
fi
""")
    return "\n".join(chunks)

def bs_curl_installers(cfg):
    chunks = []
    for entry in cfg.get("curl_installers", []):
        name = entry["name"]
        url = entry["url"]
        check = entry.get("check", "")
        nc = note_comment(entry)

        apt_deps = entry.get("apt_deps", [])
        dep_block = ""
        if apt_deps:
            deps = " \\\n    ".join(apt_deps)
            dep_block = f"sudo {APT_NI} install \\\n    {deps}\n"

        zshrc = entry.get("zshrc_block")
        zshrc_block = ""
        if zshrc:
            content = zshrc["content"].rstrip()
            marker = zshrc["marker"]
            zshrc_block = f'\nensure_block "{marker}" \\\n\'{content}\''

        if check:
            body = textwrap.dedent(f"""\
                log "Install: {name}{nc}"
                if ! {check}; then
                  {dep_block}  curl -fsSL {url} | bash
                  ok "{name} installed"
                else
                  ok "{name} already present"
                fi{zshrc_block}
                """)
        else:
            body = textwrap.dedent(f"""\
                log "Install: {name}{nc}"
                {dep_block}curl -fsSL {url} | bash
                ok "{name} installed"{zshrc_block}
                """)
        chunks.append(body)
    return "\n".join(chunks)

def bs_git_clones(cfg):
    chunks = []
    for entry in cfg.get("git_clones", []):
        name = entry["name"]
        url = entry["url"]
        dest = entry["dest"].replace("~", "$HOME")
        depth_flag = f"--depth={entry['depth']}" if "depth" in entry else ""

        zshrc = entry.get("zshrc_block")
        zshrc_block = ""
        if zshrc:
            content = zshrc["content"].rstrip()
            marker = zshrc["marker"]
            zshrc_block = f'\nensure_block "{marker}" \\\n\'{content}\''

        chunks.append(f"""\
log "Git clone: {name}"
if [[ ! -d "{dest}" ]]; then
  git clone {depth_flag} {url} "{dest}"
  ok "{name} cloned"
else
  ok "{name} already present"
fi{zshrc_block}
""")
    return "\n".join(chunks)

def bs_cleanup():
    return f"""\
log "APT cleanup"
sudo {APT_NI} autoremove
ok "Done"
"""

def bs_next_steps(cfg):
    actions = collect_actions(cfg)
    global_notes = cfg.get("post_bootstrap_notes", [])

    def to_checklist_item(text):
        lines = text.strip().splitlines()
        first = f"- [ ] {lines[0]}"
        rest = ["  " + l for l in lines[1:]]
        return "\n".join([first] + rest)

    checklist_items = []
    for note in global_notes:
        checklist_items.append(to_checklist_item(note))
    for _, action in actions:
        checklist_items.append(to_checklist_item(action))

    checklist = "\n".join(checklist_items)
    date_line = "Generated: $(date -Is)"

    return f"""\
NEXT_STEPS="$HOME/bootstrap-next-steps.md"
cat > "$NEXT_STEPS" <<NEXTSTEPS
# Bootstrap Next Steps
{date_line}

## Manual actions required

{checklist}
NEXTSTEPS

log "Bootstrap complete"
echo ""
echo "Next steps written to: $NEXT_STEPS"
echo ""
glow "$NEXT_STEPS" 2>/dev/null || cat "$NEXT_STEPS"
"""


# ── maintenance sections ──────────────────────────────────────────────────────

def maint_header():
    return f"""\
#!/usr/bin/env bash
{GENERATED_BANNER}
{DO_NOT_EDIT}
# maintenance.sh — keep the workbench up to date
set -euo pipefail

LOGFILE="$HOME/maintenance.log"
mkdir -p "$(dirname "$LOGFILE")"
exec > >(tee -a "$LOGFILE") 2>&1
trap 'rc=$?; echo "Maintenance finished with exit code $rc at $(date -Is)"; exit $rc' EXIT

echo "Maintenance started: $(date -Is)"
echo "Logfile: $LOGFILE"
{SHARED_HELPERS}
export DEBIAN_FRONTEND=noninteractive
export PATH="$HOME/.local/bin:$HOME/.npm-global/bin:$PATH"
"""

def maint_apt():
    return f"""\
log "APT: update/upgrade/autoremove"
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get autoremove -y
ok "apt updated"
"""

def maint_github_releases(cfg):
    chunks = []
    for entry in cfg.get("github_releases", []):
        name = entry["name"]
        repo = entry["repo"]
        url_tpl = entry["url"].replace("{repo}", repo)
        binary = entry["binary"]
        version_cmd = entry["version_cmd"]
        NAME = name.upper()
        chunks.append(f"""\
log "Update: {name}"
if command -v {name} >/dev/null 2>&1; then
  {NAME}_CURR="$({version_cmd} 2>/dev/null | sed 's/^v//' || true)"
  {NAME}_LATEST="$(fetch_latest_version {repo})"
  if [[ -n "${NAME}_CURR" ]] && ! semver_lt "${NAME}_CURR" "${NAME}_LATEST"; then
    ok "{name} already current (v${NAME}_CURR)"
  else
    install_release_binary_tarball \\
      "${NAME}_LATEST" \\
      "{url_tpl}" \\
      "{binary}" \\
      "{name}"
    ok "{name} updated: v${NAME}_CURR -> v${NAME}_LATEST"
  fi
else
  warn "{name} not installed; skipping"
fi
""")
    return "\n".join(chunks)

def maint_npm(cfg):
    chunks = []
    for entry in cfg.get("npm", []):
        name = entry["name"]
        bin_ = entry["bin"]
        chunks.append(f"""\
log "npm update: {name}"
if command -v npm >/dev/null 2>&1; then
  before="$(npm list -g --depth=0 {name} 2>/dev/null | grep '{name}' | sed 's/.*@//' || echo none)"
  npm install -g {name}@latest
  after="$(npm list -g --depth=0 {name} 2>/dev/null | grep '{name}' | sed 's/.*@//' || echo unknown)"
  if [[ "$before" == "$after" ]]; then
    ok "{bin_} already up to date ($after)"
  else
    ok "{bin_} updated: $before -> $after"
  fi
else
  warn "npm not found; skipping {name}"
fi
""")
    return "\n".join(chunks)

def maint_curl_installers(cfg):
    chunks = []
    for entry in cfg.get("curl_installers", []):
        name = entry["name"]
        maintenance = entry.get("maintenance", "")
        if maintenance == "git-pull":
            dest = f"$HOME/.{name}"
            chunks.append(f"""\
log "Update: {name} (git pull)"
if [[ -d "{dest}/.git" ]]; then
  git -C "{dest}" pull --ff-only || warn "{name} pull failed"
  if [[ -d "{dest}/plugins" ]]; then
    for d in "{dest}"/plugins/*; do
      [[ -d "$d/.git" ]] || continue
      git -C "$d" pull --ff-only || warn "{name} plugin update failed: $(basename "$d")"
    done
  fi
  ok "{name} updated"
else
  warn "{name} not installed; skipping"
fi
""")
        else:
            note = entry.get("note", "")
            chunks.append(f"""\
log "Check: {name}"
if command -v {name} >/dev/null 2>&1; then
  ok "{name}: $({name} --version 2>/dev/null || echo installed){' — ' + note if note else ''}"
else
  warn "{name} not found"
fi
""")
    return "\n".join(chunks)

def maint_git_clones(cfg):
    chunks = []
    for entry in cfg.get("git_clones", []):
        name = entry["name"]
        dest = entry["dest"].replace("~", "$HOME")
        chunks.append(f"""\
log "Update: {name}"
if [[ -d "{dest}/.git" ]]; then
  git -C "{dest}" pull --ff-only
  ok "{name} updated"
else
  warn "{name} not installed; skipping"
fi
""")
    return "\n".join(chunks)

def maint_summary(cfg):
    lines = []
    all_tools = []
    for section in ("apt_repos", "github_releases", "npm", "curl_installers", "git_clones"):
        for entry in cfg.get(section, []):
            bin_ = entry.get("bin", entry["name"])
            all_tools.append(bin_)

    for tool in all_tools:
        lines.append(f'printf "  %-14s %s\\n" "{tool}:" "$({tool} --version 2>/dev/null | head -1 || echo n/a)"')

    body = "\n".join(lines)
    return f"""\
log "Version summary"
{body}

log "Maintenance complete"
"""


# ── main ──────────────────────────────────────────────────────────────────────

def build_bootstrap(cfg):
    parts = [
        bs_header(),
        bs_apt(cfg),
        bs_services(cfg),
        bs_ssh_hardening(),
        bs_shell(cfg),
        bs_paths(cfg),
        bs_apt_repos(cfg),
        bs_github_releases(cfg),
        bs_npm(cfg),
        bs_curl_installers(cfg),
        bs_git_clones(cfg),
        bs_cleanup(),
        bs_next_steps(cfg),
    ]
    return "\n".join(parts)

def build_maintenance(cfg):
    parts = [
        maint_header(),
        maint_apt(),
        maint_github_releases(cfg),
        maint_npm(cfg),
        maint_curl_installers(cfg),
        maint_git_clones(cfg),
        maint_summary(cfg),
    ]
    return "\n".join(parts)

def main():
    cfg = yaml.safe_load(TOOLS_YAML.read_text())

    bootstrap = build_bootstrap(cfg)
    BOOTSTRAP_OUT.write_text(bootstrap)
    BOOTSTRAP_OUT.chmod(0o755)
    print(f"wrote {BOOTSTRAP_OUT}")

    maintenance = build_maintenance(cfg)
    MAINTENANCE_OUT.write_text(maintenance)
    MAINTENANCE_OUT.chmod(0o755)
    print(f"wrote {MAINTENANCE_OUT}")

if __name__ == "__main__":
    main()
