#!/usr/bin/env bash
# Generated by generate.py from tools.yaml on 2026-03-17 00:46 UTC
# DO NOT edit this file directly — edit tools.yaml and re-run: python3 generate.py
# maintenance.sh — keep the workbench up to date
set -euo pipefail

LOGFILE="$HOME/maintenance.log"
mkdir -p "$(dirname "$LOGFILE")"
exec > >(tee -a "$LOGFILE") 2>&1
trap 'rc=$?; echo "Maintenance finished with exit code $rc at $(date -Is)"; exit $rc' EXIT

echo "Maintenance started: $(date -Is)"
echo "Logfile: $LOGFILE"

log()  { printf "\n==> %s\n" "$*"; }
ok()   { printf "    \u2713 %s\n" "$*"; }
warn() { printf "    ! %s\n" "$*"; }

ensure_block() {
  local marker="$1" content="$2"
  if ! grep -qF "$marker" "$HOME/.zshrc"; then
    printf "\n%s\n%s\n" "$marker" "$content" >> "$HOME/.zshrc"
    ok "Added block: $marker"
  else
    ok "Block already present: $marker"
  fi
}

fetch_latest_version() {
  curl -fsSL "https://api.github.com/repos/$1/releases/latest" | jq -r '.tag_name' | sed 's/^v//'
}

install_release_binary_tarball() {
  local version="$1" url_tpl="$2" bin_in="$3" target="$4"
  local url tmp
  url="${url_tpl//\{version\}/$version}"
  tmp="$(mktemp -d)"
  curl -fsSL "$url" -o "$tmp/pkg.tgz"
  tar -xzf "$tmp/pkg.tgz" -C "$tmp" "$bin_in"
  install -m 755 "$tmp/$bin_in" "$HOME/.local/bin/$target"
  rm -rf "$tmp"
}

semver_lt() {
  [[ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | head -n1)" == "$1" && "$1" != "$2" ]]
}

export DEBIAN_FRONTEND=noninteractive
export PATH="$HOME/.local/bin:$HOME/.npm-global/bin:$PATH"

log "APT: update/upgrade/autoremove"
sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get autoremove -y
ok "apt updated"

log "Update: fzf"
if command -v fzf >/dev/null 2>&1; then
  FZF_CURR="$(fzf --version | awk '{print $1}' 2>/dev/null | sed 's/^v//' || true)"
  FZF_LATEST="$(fetch_latest_version junegunn/fzf)"
  if [[ -n "$FZF_CURR" ]] && ! semver_lt "$FZF_CURR" "$FZF_LATEST"; then
    ok "fzf already current (v$FZF_CURR)"
  else
    install_release_binary_tarball \
      "$FZF_LATEST" \
      "https://github.com/junegunn/fzf/releases/download/v{version}/fzf-{version}-linux_amd64.tar.gz" \
      "fzf" \
      "fzf"
    ok "fzf updated: v$FZF_CURR -> v$FZF_LATEST"
  fi
else
  warn "fzf not installed; skipping"
fi

log "Update: navi"
if command -v navi >/dev/null 2>&1; then
  NAVI_CURR="$(navi --version | awk '{print $2}' 2>/dev/null | sed 's/^v//' || true)"
  NAVI_LATEST="$(fetch_latest_version denisidoro/navi)"
  if [[ -n "$NAVI_CURR" ]] && ! semver_lt "$NAVI_CURR" "$NAVI_LATEST"; then
    ok "navi already current (v$NAVI_CURR)"
  else
    install_release_binary_tarball \
      "$NAVI_LATEST" \
      "https://github.com/denisidoro/navi/releases/download/v{version}/navi-v{version}-x86_64-unknown-linux-musl.tar.gz" \
      "navi" \
      "navi"
    ok "navi updated: v$NAVI_CURR -> v$NAVI_LATEST"
  fi
else
  warn "navi not installed; skipping"
fi

log "Update: zellij"
if command -v zellij >/dev/null 2>&1; then
  ZELLIJ_CURR="$(zellij --version | awk '{print $2}' 2>/dev/null | sed 's/^v//' || true)"
  ZELLIJ_LATEST="$(fetch_latest_version zellij-org/zellij)"
  if [[ -n "$ZELLIJ_CURR" ]] && ! semver_lt "$ZELLIJ_CURR" "$ZELLIJ_LATEST"; then
    ok "zellij already current (v$ZELLIJ_CURR)"
  else
    install_release_binary_tarball \
      "$ZELLIJ_LATEST" \
      "https://github.com/zellij-org/zellij/releases/download/v{version}/zellij-x86_64-unknown-linux-musl.tar.gz" \
      "zellij" \
      "zellij"
    ok "zellij updated: v$ZELLIJ_CURR -> v$ZELLIJ_LATEST"
  fi
else
  warn "zellij not installed; skipping"
fi

log "Update: lazygit"
if command -v lazygit >/dev/null 2>&1; then
  LAZYGIT_CURR="$(lazygit --version | sed -n 's/.*version=\([^, ]*\).*/\1/p' 2>/dev/null | sed 's/^v//' || true)"
  LAZYGIT_LATEST="$(fetch_latest_version jesseduffield/lazygit)"
  if [[ -n "$LAZYGIT_CURR" ]] && ! semver_lt "$LAZYGIT_CURR" "$LAZYGIT_LATEST"; then
    ok "lazygit already current (v$LAZYGIT_CURR)"
  else
    install_release_binary_tarball \
      "$LAZYGIT_LATEST" \
      "https://github.com/jesseduffield/lazygit/releases/download/v{version}/lazygit_{version}_Linux_x86_64.tar.gz" \
      "lazygit" \
      "lazygit"
    ok "lazygit updated: v$LAZYGIT_CURR -> v$LAZYGIT_LATEST"
  fi
else
  warn "lazygit not installed; skipping"
fi

log "npm update: @openai/codex"
if command -v npm >/dev/null 2>&1; then
  before="$(npm list -g --depth=0 @openai/codex 2>/dev/null | grep '@openai/codex' | sed 's/.*@//' || echo none)"
  npm install -g @openai/codex@latest
  after="$(npm list -g --depth=0 @openai/codex 2>/dev/null | grep '@openai/codex' | sed 's/.*@//' || echo unknown)"
  if [[ "$before" == "$after" ]]; then
    ok "codex already up to date ($after)"
  else
    ok "codex updated: $before -> $after"
  fi
else
  warn "npm not found; skipping @openai/codex"
fi

log "Update: pyenv (git pull)"
if [[ -d "$HOME/.pyenv/.git" ]]; then
  git -C "$HOME/.pyenv" pull --ff-only || warn "pyenv pull failed"
  if [[ -d "$HOME/.pyenv/plugins" ]]; then
    for d in "$HOME/.pyenv"/plugins/*; do
      [[ -d "$d/.git" ]] || continue
      git -C "$d" pull --ff-only || warn "pyenv plugin update failed: $(basename "$d")"
    done
  fi
  ok "pyenv updated"
else
  warn "pyenv not installed; skipping"
fi

log "Check: atuin"
if command -v atuin >/dev/null 2>&1; then
  ok "atuin: $(atuin --version 2>/dev/null || echo installed) — Shell history sync and search"
else
  warn "atuin not found"
fi

log "Check: zoxide"
if command -v zoxide >/dev/null 2>&1; then
  ok "zoxide: $(zoxide --version 2>/dev/null || echo installed) — Smarter cd — use 'z' instead of 'cd'"
else
  warn "zoxide not found"
fi

log "Check: claude"
if command -v claude >/dev/null 2>&1; then
  ok "claude: $(claude --version 2>/dev/null || echo installed) — Claude Code CLI — self-updates, no maintenance step needed"
else
  warn "claude not found"
fi

log "Update: zsh-completions"
if [[ -d "$HOME/.zsh/zsh-completions/.git" ]]; then
  git -C "$HOME/.zsh/zsh-completions" pull --ff-only
  ok "zsh-completions updated"
else
  warn "zsh-completions not installed; skipping"
fi

log "Version summary"
printf "  %-14s %s\n" "gh:" "$(gh --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "nodejs:" "$(nodejs --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "glow:" "$(glow --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "fzf:" "$(fzf --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "navi:" "$(navi --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "zellij:" "$(zellij --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "lazygit:" "$(lazygit --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "codex:" "$(codex --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "pyenv:" "$(pyenv --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "atuin:" "$(atuin --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "zoxide:" "$(zoxide --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "claude:" "$(claude --version 2>/dev/null | head -1 || echo n/a)"
printf "  %-14s %s\n" "zsh-completions:" "$(zsh-completions --version 2>/dev/null | head -1 || echo n/a)"

log "Maintenance complete"
